shallow_clone: true
clone_depth: 1
platform:
  - x86
  - x64
configuration:
  - Release
image: Visual Studio 2015
init:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop update
  - ps: $ErrorActionPreference = 'SilentlyContinue'; scoop bucket add extras
install:
  - ps: scoop install libsndfile cmake pkg-config --arch $env:PLATFORM
build_script:
  - ps: cmake $env:APPVEYOR_BUILD_FOLDER
  - ps: cmake --build $env:APPVEYOR_BUILD_FOLDER
