shallow_clone: true
clone_depth: 1
platform:
  - x86
  - x64
configuration:
  - Release
image: Visual Studio 2013
init:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop update
  - ps: $ErrorActionPreference = 'SilentlyContinue'; scoop bucket add extras
  - ps: If ("$env:PLATFORM" -eq "x86") { $env:ARCH="32bit" } Else { $env:ARCH="64bit" }
install:
  - ps: scoop install --arch $env:ARCH libsndfile
before_build:
  - # FIXME Does this need to be hard coded
  - ps: $env:VSBIN  = "${env:ProgramFiles(x86)}\Microsoft Visual Studio 12.0\VC\bin"
  - ps: $env:VSKIT  = "${env:ProgramFiles(x86)}\Windows Kits\8.0\Lib\win8\um\$env:PLATFORM"
  - ps: $env:SRC    = "$env:APPVEYOR_BUILD_FOLDER"
  - ps: $env:VSPATH = "$(."$env:SRC\Win32\shortname.cmd" "$env:VSBIN\..")"
  - ps: $env:PATH   = "$env:VSBIN;$env:PATH"
  - ps: echo "Using"
  - ps: echo "   env:VSBIN  = $env:VSBIN"
  - ps: echo "   env:VSPATH = $env:VSPATH"
  - ps: echo "   env:SRC    = $env:SRC"
  - #
  - cmd: mklink /h %VSPATH%\Lib\kernel32.lib "%VSKIT%\kernel32.lib"
  - cmd: mklink /h %SRC%\libsndfile-1.dll "%userprofile%\scoop\apps\libsndfile\current\bin\libsndfile-1.dll"
  - cmd: mklink /h %SRC%\libsndfile-1.lib "%userprofile%\scoop\apps\libsndfile\current\lib\libsndfile-1.lib"
  - cmd: mklink /h %SRC%\libsndfile-1.def "%userprofile%\scoop\apps\libsndfile\current\lib\libsndfile-1.def"
  - cmd: mklink /h %SRC%\Win32\sndfile.h "%userprofile%\scoop\apps\libsndfile\current\include\sndfile.h"
  - ps: sc $env:SRC\Win32\Makefile.msvc ((gc $env:SRC\Win32\Makefile.msvc) -replace "^MSVCDir=.*","MSVCDir=$env:VSPATH")
build_script:
  - ps: cd $env:SRC; .\Make.bat
