shallow_clone: true
clone_depth: 1
platform:
  - x86
  - x64
configuration:
  - Release
image: Visual Studio 2015
init:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop bucket add extras
install:
  - ps: scoop install libsndfile
before_build:
  - cmd: mklink /h libsndfile-1.dll "%userprofile%\scoop\apps\libsndfile\current\bin\libsndfile-1.dll"
  - cmd: mklink /h libsndfile-1.lib "%userprofile%\scoop\apps\libsndfile\current\bin\libsndfile-1.lib"
  - cmd: mklink /h libsndfile-1.def "%userprofile%\scoop\apps\libsndfile\current\lib\libsndfile-1.def"
  - cmd: mklink /h Win32/sndfile.h "%userprofile%\scoop\apps\libsndfile\current\include\sndfile.h"
build_script:
  - ps: $vsbin = $(cmd /c where cl)
  - ps: cd $vsbin; cd ..; $vspath = $(.\Win32\shortname.cmd .)
  - ps: sc Win32\Makefile.msvc ((gc Win32\Makefile.msvc) -replace "^MSVCDir=.*","MSVCDir=$vspath")
  - ps: .\Make.bat
