shallow_clone: true
clone_depth: 1
platform:
  - x86
  - x64
configuration:
  - Release
image: Visual Studio 2013
init:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: $ErrorActionPreference = 'SilentlyContinue'; scoop bucket add extras #Why does AppVeyor hate this
install:
  - ps: scoop install libsndfile
before_build:
  - ps: $env:src = $env:APPVEYOR_BUILD_FOLDER
  - cmd: mklink /h %src%\libsndfile-1.dll "%userprofile%\scoop\apps\libsndfile\current\bin\libsndfile-1.dll"
  - cmd: mklink /h %src%\libsndfile-1.lib "%userprofile%\scoop\apps\libsndfile\current\lib\libsndfile-1.lib"
  - cmd: mklink /h %src%\libsndfile-1.def "%userprofile%\scoop\apps\libsndfile\current\lib\libsndfile-1.def"
  - cmd: mklink /h %src%\Win32\sndfile.h "%userprofile%\scoop\apps\libsndfile\current\include\sndfile.h"
build_script:
  - ps: $vsbin = "${env:ProgramFiles(x86)}\Microsoft Visual Studio 12.0\VC\bin" #Does this need to be hardcoded
  - ps: echo "vsbin = ${vsbin}"
  - ps: cd "$vsbin"; cd ..; $vspath = $(.$env:src\Win32\shortname.cmd .)
  - ps: echo "vspath =  $vspath"
  - ps: sc $env:src\Win32\Makefile.msvc ((gc $env:src\Win32\Makefile.msvc) -replace "^MSVCDir=.*","MSVCDir=$vspath")
  - ps: $env:PATH="$vsbin;$env:PATH"
  - ps: cd $env:src; .\Make.bat
